title: Tushar Muley # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <img align="center" src="images/tushar.jpg" width="200" height="225" />
  <br><br>
  <a href="/about.html">About Me</a> | <a href="/contact.html">Contact</a>
  <br><br>
  Connect with me:
  <br>
  <a href="https://www.linkedin.com/in/tusharmuley/"><img src="images/linkedin.png" width="50" height="50" /></a>
  <a href="https://github.com/tushar-muley"><img src="images/github.png" width="50" height="50" /></a>
  <br><br>
  <h3>Skills</h3>
  <p align="justify">Python Programming, R Programming, SQL, Data Preparation (Wrangling/Denodo), Data Mining, Exploratory Data Analysis, 
  Predictive Analytics, Machine Learning, Data Visualization (Tableau/MicroStrategy/DOMO), Big Data</p>
  <br><br>
theme: jekyll-theme-minimal
