title: Tushar Muley
description: 
<br><br>
About Me:
<br>
I'm working as Sr. Data Engineer for a Fincial Company in Phx, Arizona. I recently graduated with a Master's degree in Data Science from Bellevue University.
<br><br>
theme: jekyll-theme-minimal
