title: Tushar Muley # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  About me: 
  <br>
  I'm currently working as a Sr. Data Engineer at American Express, Phoenix, AZ. I recently graduated with a Master's degree in Data Science from Bellevue University.
  I'm passionate about data analysis, data science and business intelligence. I consider myself a data junky.
  <br><br>
  Connect with me:
  <br>
  
  <br><br>
  <br><br>
theme: jekyll-theme-minimal
